data:
  dir: /mnt/c/Users/amehedi/Downloads/ml_debris/output/thomas
  target_name: dem_diff.tif
  include_names:
    - burn__severity.tif
    - cation__exchange_capacity.tif
    - clay__total.tif
    - dry__bulk_density.tif
    - field__capacity.tif
    - landcover.tif
    - pH.tif
    - porosity.tif
    - sand__total.tif
    - saturated__water_content.tif
    - silt__total.tif
    - soil__density.tif
    - soil__internal_friction_angle.tif
    - soil__maximum_total_cohesion.tif
    - soil__minimum_total_cohesion.tif
    - soil__mode_total_cohesion.tif
    - soil__saturated_hydraulic_conductivity.tif
    - soil__texture.tif
    - soil__thickness.tif
    - soil__transmissivity.tif
    - topographic__elevation.tif
    - vegetation__plant_functional_type.tif
    - wilting__point.tif

split:
  method: spatial_block_cv
  test_size: 0.2
  block_size: 64
  n_folds: 5
  selection_metric: rmse
  random_state: 42

model:
  type: rf
  n_estimators: 300
  max_depth: null
  min_samples_leaf: 1
  random_state: 42
  n_jobs: 8
  #Optional tuning grid used only with split.method=spatial_block_cv
  search_grid:
    n_estimators: [20, 30, 50]
    # max_depth: [null, 20]
    # min_samples_leaf: [1, 5]

output:
  model_dir: models/rf
  run_prefix: rf
